name: phase-2-practice

on: push

jobs:
  phase2:
    runs-on: ubuntu-latest
    steps:
      - name: Checking befor downloading repo 
        run: ls -la

      - name: checkout repo
        uses: actions/checkout@v4
        
      - name: Checking after downloading repo 
        run: ls -la

      - name: checkout .github 
        run: ls .github/workflows 