name: phase-2-practice

on: push

jobs:
  phase2:
    runs-on: ubuntu-latest
    steps:
      - name: Checking befor downloading repo 
        run: ls -la

      - name: checkout repo
        uses: actions/checkout@v4
        
      - name: Checking after downloading repo 
        run: ls -la

      - name: checkout .github 
        run: ls .github/workflows 

      - name: create file 
        run: echo "uploading artifact" > result.txt

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: result artifact
          path: result.txt