name: secret-test
on: push

jobs: 
  testing-secrets:
    runs-on: ubuntu-latest
    steps: 
      - name: Use secrets
        run: |
         echo " ${{secret.MY_NAME}}"
         echo " ${{secret.MY_ROLE}}"