name: secret-test
on: push

jobs: 
  testing-secrets:
    runs-on: ubuntu-latest
    environment: dev 
    steps: 
      - name: Use env secrets
        run: |
         echo "My Name : ${{secrets.MY_NAME}}"
         echo "My Role : ${{secrets.MY_ROLE}}"

      - name: Use repo secrets
        run: |
         echo "My Name : ${{secrets.My_Name}}"
         echo "My Role : ${{secrets.My_Role}}"

      - name: Use Environment
        run: |
         echo "Environment : ${{secret.App_ENV}}"