name: secret-test
on: push

jobs: 
  testing-secrets:
    runs-on: ubuntu-latest
    Environment: TESTING 
    steps: 
      - name: Use secrets
        run: |
         echo "My Name : ${{secrets.MY_NAME}}"
         echo "My Role : ${{secrets.MY_ROLE}}"