name: secret-test
on: push

jobs: 
  testing-secrets:
    runs-on: ubuntu-latest
    environment: dev 
    env: 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps: 
      - name: Use env secrets
        run: |
         echo "My Name : ${{secrets.MY_NAME}}"
         echo "My Role : ${{secrets.MY_ROLE}}"

      - name: Use repo secrets
        run: |
         echo "My Name : ${{secrets.My_Name}}"
         echo "My Role : ${{secrets.My_Role}}"

      - name: Use Environment
        run: |
         echo "Environment : ${{secrets.App_ENV}}"

      