name: phase-2-steps-practice

on:
  push:
  workflow_dispatch:

jobs:
  step_test:
    runs-on: ubuntu-latest
    steps:  
      - name: step-1 
        run: echo "step 1 started"

      - name: step-2  
        run: echo "step 2 running"
      
      - name: step 3  
        run: uname -a

      - name: failed step
        run: hello this is failed 